// const express = require("express");
// const nodemailer = require("nodemailer");
// const validator = require("validator");
// const xssFilters = require("xss-filters");

// const app = express();

// app.use(express.json());

// app.get("/", function(req, res) {
//   res.status(405).json({ error: "sorry!" });
// });

// app.post("/", function(req, res) {
//   let transporter = nodemailer.createTransport({
//     host: "smtp.mailtrap.io",
//     port: 587,
//     auth: {
//       user: "ea828d89ddb1b5", //generated by Mailtrap
//       pass: "63ed45c17acf1a" //generated by Mailtrap
//     },
//     tls: { rejectUnauthorized: false }
//   });

//   var mailOptions = {
//     from: '"Example Team" <from@example.com>',
//     to: "declanleebaldwin@gmail.com",
//     subject: "Nice Nodemailer test",
//     text: "Hey there, it’s our first message sent with Nodemailer ;) ",
//     html:
//       "<b>Hey there! </b><br> This is our first message sent with Nodemailer"
//   };

//   transporter.sendMail(mailOptions, (error, info) => {
//     if (error) {
//       console.log(error);
//       res.status(200).json({ message: error });
//     } else {
//       res.status(200).json({ message: "pass" });
//       console.log("Message sent: %s", info.messageId);
//     }
//   });
// });

// module.exports = {
//   path: "/api/contact",
//   handler: app
// };

const express = require('express')
const nodemailer = require('nodemailer')
const validator = require('validator')
const xssFilters = require('xss-filters')

const app = express()

app.use(express.json())

app.get('/', function (req, res) {
  res.status(405).json({ error: 'sorry!' })
})

app.post('/', function (req, res) {
  const attributes = ['name', 'email', 'message']
  const sanitizedAttributes = attributes.map(n => validateAndSanitize(n, req.body[n]))
  const someInvalid = sanitizedAttributes.some(r => !r)

  if (someInvalid) {
    return res.status(422).json({ 'error': 'Ugh.. That looks unprocessable!' })
  }

  sendMail(...sanitizedAttributes)
  res.status(200).json({ 'message': 'OH YEAH' })
})
module.exports = {
  path: '/api/contact',
  handler: app
}

const validateAndSanitize = (key, value) => {
  const rejectFunctions = {
    name: v => v.length < 2,
    email: v => !validator.isEmail(v),
    message: v => v.length < 2
  }

  // If object has key and function returns false, return sanitized input. Else, return false
  return rejectFunctions.hasOwnProperty(key) && !rejectFunctions[key](value) && xssFilters.inHTMLData(value)
}

const sendMail = (name, email, message) => {
  let transporter = nodemailer.createTransport({
    host: "smtp.mailtrap.io",
        port: 587,
        auth: {
          user: "ea828d89ddb1b5", //generated by Mailtrap
          pass: "63ed45c17acf1a" //generated by Mailtrap
        },
        tls: { rejectUnauthorized: false }
  })
  transporter.sendMail({
    from: email,
    to: 'declanleebaldwin@gmail.com',
    subject: 'New contact form message',
    text: message
  })
}

